export enum ProcurementStatusEnum {
  ORDER_ITEM_CART = 0,
  QUOTATION_REPLY = 1,
  PURCHASE_APRROVAL_REQUEST = 2,
  PURCHASE_ORDER_APPROVAL = 3,
  ARRIVAL_SCHEDULE_REGISTRATION = 4,
  ORDER = 5,
  ORDERED = 6,
}
