export default interface Base {
  baseId?: string,
  baseName?: string,
  baseCd?: string,
  zipCode?: string,
  prefCode?: number,
  address?: string,
  addressee?: string,
  eMailAddress?: string,
  telephoneNumber?: number,
  faxNumber?: number,
  note?: string,
  version?: number,
  createdAt?: string,
  modifiedAt?: string,
  deletedAt?: string,
  isDeleted?: boolean,
}
